### ISSUE TITLE
about the gauss_params["colors"] 

### ISSUE THREAD

**Issue by Korace0v0** [KevinXu02/splatfacto-w#10]
Hi, may I ask if the `base_colors` in `SplatfactoWModel`  has been deprecated?  

It seems that the input of rasterizer only use colors derived from `appearance_features`. But the ` gauss_params["colors"] ' still appears in the densification process, which is a little bit strange.

Thanks a lot!

**Comment by KevinXu02** [comment]
Yes, we don't use base_colors in splatfactow. 
`gauss_params["colors"] ` were used for letting mlp to predict the colors from sfm in the beginning with zero init, but this feature has't been implemented in the current version.

**Comment by Korace0v0** [comment]
I understand it. Thank you very much!
