### ISSUE TITLE
How to export PLY file?

### ISSUE THREAD

**Issue by cainiaoshidai** [KevinXu02/splatfacto-w#11]
Hi,
It's a very nice work. I get a nice result on my data. But I don't know how to export ply model. Can you give me some advice. Thanks.
Best

**Comment by KevinXu02** [comment]
Hi! I added a simple scipt to export ply files, please see readme for instructions.

**Comment by xuxumiao777** [comment]
> Hi! I added a simple scipt to export ply files, please see readme for instructions.

Hi！I have used your script and have generated ply. However, the sky does not exist. I guess the sky cannot be rendered without gpu?

**Comment by KevinXu02** [comment]
The sky is rendered with a separated logic and cannot be exported as ply file. You might need to turn off the bg model if you want to see the sky in other ply viewers.
