### ISSUE TITLE
splatfacto-w vs splatfacto-w-light 

### ISSUE THREAD

**Issue by maturk** [KevinXu02/splatfacto-w#15]
Hi @KevinXu02, I had a small question:

What are the differences between `splatfacto-w` and `splatfacto-w-light` models? Is it just that the dataparser/datamanagers are different, or are the architectural changes?

**Comment by KevinXu02** [comment]
Hi! splatfacto-w uses a deeper MLP with more dim for appearance embeddings as well as the feature dim in each gaussian, while the light verson uses smaller ones. Generally speaking `splatfacto-w-light` should be faster with less GRAM usage.

**Comment by mluogh** [comment]
Is that the only difference? Would I get the same thing as splatfacto-w if I just copied the config but used normal nerfstudio dataparsers like splatfacto-w-light does?

Why does splatfacto-w dataparser required a dense reconstruction?

Would be good to document this somewhere.
