### ISSUE TITLE
How to calculate evaluation?

### ISSUE THREAD

**Issue by JeremyChouJI** [KevinXu02/splatfacto-w#16]
Thanks for your great work. I have a quick question. I am training my own dataset using the CLI `splatfacto-w-light`. For the results I obtained, when calculating the PSNR, should I directly use the original Nerfstudio CLI `ns-eval`?

Here is the command I used to calculate the evaluation: 
`ns-eval --load-config /home/jeremy/outputs/mytable/splatfacto-w-light/2024-10-16_125403/config.yml --output-path /home/jeremy/eval/mytable.json`

 It works, but I wonder if using the original Nerfstudio CLI ns-eval will give me the correct value.

**Comment by KevinXu02** [comment]
Yes, `ns-eval` should work for `splatfacto-w-light`. During eval it will use the average appearance embedding for inference, so it might be not precise if your photos change a lot. And the eval part for splatw uses a different logic from  `splatfacto-w-light` which currently only works for phototourism.

**Comment by JeremyChouJI** [comment]
Thank you for your reply!
I just want to confirm: when you refer to `splatw`, are you referring to `splatfacto-w`?

**Comment by KevinXu02** [comment]
Yes!

**Comment by JeremyChouJI** [comment]
OK.  I understand. Thank you again for your great work and reply!
