### ISSUE TITLE
`from gsplat.cuda_legacy._torch_impl import quat_to_rotmat` broken in gsplat 1.4

### ISSUE THREAD

**Issue by Parskatt** [KevinXu02/splatfacto-w#17]
This line 
https://github.com/KevinXu02/splatfacto-w/blob/main/splatfactow/splatfactow_model.py#L30

Doesn't work with `gsplat==1.4`, but works with `gsplat==1.3`

**Comment by KevinXu02** [comment]
Hi! Could you please try the latest code? I've updated it to support `gsplat==1.4`.

**Comment by Parskatt** [comment]
Working, thanks.
