### ISSUE TITLE
Cannot change appearance

### ISSUE THREAD

**Issue by edmondeng** [KevinXu02/splatfacto-w#2]
After installing, I can train the model using
`ns-train splatfacto-w --data /home/edmonde/Documents/dataset/trevi_fountain/`
which that path contains:
├── brandenburg.tsv
├── camera_paths
│   └── 2024-07-15-11-00-47.json
└── dense
    ├── images/(jpgs from set)
    ├── sparse/sparse (cameras.bin, image.bin, points3D.bin)
    └── stereo(depthmaps, depth_maps_clean_300_th_0.10,pairs-dilation-0.00-fixed2.h5)

But when using the ns-viewer while I can navigate and render the splats out. I cannot change the appearance by clicking a camera view. 

What are the steps or things i can look for to debug this? I would like to know how to determine if my issue is the data or the viewer. 

e

**Comment by KevinXu02** [comment]
The code part for view changing hasn't been merged into main nerfstudio branch yet. You might need to manually clone this pr https://github.com/nerfstudio-project/nerfstudio/pull/3293.

**Comment by edmondeng** [comment]
ok great thanks!!!
