### ISSUE TITLE
About tsv file

### ISSUE THREAD

**Issue by seulqxq** [KevinXu02/splatfacto-w#23]
Hi, I'm a little confused about the tsv file for this dataset, how should I generate this tsv file if I use my own dataset?

**Comment by KevinXu02** [comment]
Hi! You can use `ns-train splatfacto-w-light` as descibed in the readme, it should be compatible with your own colmap/nerfstudio dataset.

**Comment by seulqxq** [comment]
Wow, thanks for your quick response, I'll give it a try.
