### ISSUE TITLE
Does the background model can reconstruct the sun or the clouds ? 

### ISSUE THREAD

**Issue by cyy1992** [KevinXu02/splatfacto-w#25]
When I used my own data to reconstruct the model with the code, I noticed that the background model failed to reconstruct the sun or clouds.

**Comment by KevinXu02** [comment]
Yes, currently the bg model can only reconstruct low frequency part in the background (eg sky). And GS would still try to reconstruct other parts.

**Comment by cyy1992** [comment]
Got it！Thank you！
