### ISSUE TITLE
How to export Splats PLY

### ISSUE THREAD

**Issue by pdxmusic** [KevinXu02/splatfacto-w#5]
Good morning!
Thanks for your awesome work, the results are amazing!

I tried to export the splats using the UI that provides the method `ns-export pointcloud` but it didn't work, I also tried to use `ns-export gaussian-splat` but I got another error.

Is the export implemented? If so which method is the correct one?

Thanks in advance.

**Comment by KevinXu02** [comment]
Hi! The export hasn't been implemented yet. It shouldn't be hard to export given a specific appearance embedding and I can add that code these days.

**Comment by paidiakileswar** [comment]
@KevinXu02 Can i know When we can expect 
`ns-export` option will be integrated into the `splatfacto - w`

**Comment by KevinXu02** [comment]
Sorry for the late update. I added a simple scipt to export ply files, please see readme for instructions.
